name: Docker Image CI

on:
  push:
    branches: [ "Actions" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd \BekProtek_S3\s3_bekprotek\application\backend\bekprotek
        docker build . --file Dockerfile --tag bekprotek-server:latest
